spring.application.name=authenticationservice
server.port=8087

# H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
# JWT
app.jwt.secret=a3f1c7d2b8e0f5a6d9c1b4f8a7e2d3c6f4b9a1e8c7d6b2f0a5c3d9e7b8f4a2c1
app.jwt.exp-minutes=1

app.jwt.refresh.secret=a3f1c7d2b8e0f5a6d9cq0m13a7e2d3c6f4b9a1e8c7d6b2f0a5c3d9e7b8f4a2c1
app.jwt.refresh.exp-minutes=10

# Allow static files (frontend) to be served
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
